In [1]:
from keras.models import Sequential 
from keras.layers import Activation, Dense, InputLayer
import tensorflow as tf
import numpy as np

In [2]:
model = Sequential()
layer_1=InputLayer(input_shape=(4,))
layer_2=Dense(7,activation='relu')
layer_3=Dense(10,activation='relu')
model.add(layer_1)
model.add(layer_2)
model.add(layer_3)
model.compile(tf.keras.optimizers.RMSprop(0.001), loss='mse')
model.summary()
model.fit(np.zeros((10, 4)),
          np.ones((10, 1)))

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 35        
                                                                 
 dense_1 (Dense)             (None, 10)                80        
                                                                 
Total params: 115
Trainable params: 115
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 1s 829ms/step - loss: 1.0000


In [4]:
layer_2.get_weights()

[array([[-0.08762354, -0.50351214, -0.1487202 , -0.55893886, -0.17640322,
          0.02421612, -0.64607376],
        [-0.68824655, -0.29146373,  0.4971344 , -0.38893035,  0.19064963,
         -0.42397752, -0.63313407],
        [ 0.4672982 , -0.70705354,  0.23470968,  0.7334103 , -0.6434742 ,
         -0.60393924,  0.34133404],
        [-0.22630394, -0.54633784, -0.25405368, -0.6187061 , -0.38531622,
          0.10183102,  0.6545184 ]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [5]:
layer_3.get_weights()

[array([[-2.79976308e-01,  7.83860683e-03,  5.00908017e-01,
         -2.09223270e-01, -1.91426694e-01, -6.42723441e-02,
         -4.69754726e-01, -9.74649489e-02,  3.67870986e-01,
          2.38712251e-01],
        [ 3.53954494e-01,  1.20812476e-01,  3.63378346e-01,
         -4.43598568e-01, -5.91480792e-01,  5.72086573e-02,
          7.90812969e-02, -3.26788336e-01, -4.95932519e-01,
         -2.75534838e-01],
        [-1.58971488e-01,  1.29550099e-01, -2.14921087e-01,
         -5.05387545e-01,  1.15592480e-02,  4.13014889e-01,
          3.04020286e-01,  3.48301470e-01,  1.27645552e-01,
         -5.30420005e-01],
        [ 1.43212974e-01, -3.22076082e-02, -2.72542387e-01,
         -1.07046872e-01,  2.68026710e-01,  3.74520481e-01,
         -5.62345207e-01, -3.45659852e-01,  1.51013196e-01,
          5.58728099e-01],
        [-5.81087708e-01,  6.55719042e-02, -5.38927734e-01,
         -2.12767571e-01, -4.81170774e-01, -4.12757516e-01,
         -5.72116256e-01, -5.70511162e-01,  5.215406

In [6]:
np.ones((4, 1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [7]:
np.zeros((10, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])